# Generated by Django 4.2.21 on 2025-05-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
